server:
  port: ${PORT:8080}
  servlet:
    context-path: /iss_365_setting

spring:
  datasource:
    url: ${POSTGRESQL_DATABASE_URL}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ducanh21112003@gmail.com
    password: ymfudurkopzezdnn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

async:
  config:
    core-pool-size: ${ASYNC_CORE_POOL_SIZE:3}
  
  
  flyway:
    locations: classpath:db/migration

jwt:
  secretKey: aHR0cHM6Ly93d3cuZXhhbXBsZS5jb20vbXktc2VjcmV0LWtleS1mb3ItaG1hYy1zaGEyNTY=